[program:consumer-high]
command=php /var/www/artisan notifications:consume --topic=high
process_name=%(program_name)s_%(process_num)02d
autostart=true
autorestart=true
startretries=10
numprocs=1
stopwaitsecs=10
startsecs=3
stdout_logfile=/var/log/supervisor/consumer-high.log
stderr_logfile=/var/log/supervisor/consumer-high.err.log

[program:consumer-low]
command=php /var/www/artisan notifications:consume --topic=low
process_name=%(program_name)s_%(process_num)02d
autostart=true
autorestart=true
startretries=10
numprocs=1
stopwaitsecs=10
startsecs=3
stdout_logfile=/var/log/supervisor/consumer-low.log
stderr_logfile=/var/log/supervisor/consumer-low.err.log
